### ISSUE TITLE
decode_export: The device property 'SerialNumber' is not set.

### ISSUE THREAD

**Issue by Tony2** [PeterPawn/decoder#26]
Hi,

[I apologize if this is not the right place to post this issue]

I am trying to decode a backup exported from my FritzBox with the following command:

```
./decoder.x86_64 decode_export -a env < FRITZ.Box\ 7272\ \(UI\)\ 120.06.88_11.03.22_1401.export
```

where`env` is a file with the following content:
```
SerialNumber    E50448830126160
maca    5C:49:79:57:47:5A
wlan_key        25083886372223913969
```

I got error 
```
decode_export: The device property 'SerialNumber' is not set.
```

Any hint what I am missing please? I use the pre-compiled binary from the latest release.

**Comment by PeterPawn** [comment]
Maybe it's a problem with the size of the real serial number. In the past, where this value was unused but taken into account while computing secrets, it's size was 16 (using "0" characters), while the real numbers (used meanwhile) have only 15 characters (grouped 4-3-2-3-3 at the back of device).

Are you sure, that your device really has the real serial number in its environment? IIRC this happened first with GRX5-based models and I'd think, your device is using the (aforementioned) "0" characters (16 times). 

On the other hand ... are you REALLY sure, that your export file was created with the default device password (which is computed from these properties) and not with a specified password? The version number from the name of your export file suggests, that it was created by a FRITZ!OS version, where the export of this file needs ALWAYS an user-specified password.

If your export file contains two password entries (where one is for a user-specified password and the other for the computed device password), it should contain two lines starting with `Password` in its header lines, the second entry using a name of `Password2`.

According to the date/time component of file name it seems, you've created this export file only a few hours ago - I'd bet, you had to specify an 'export password' and if I'm right, you should call the command with this password instead of the `-a env` part.

Nevertheless I'll check again, whether my verifications for the size of the `SerialNumber` value are correct in this place - I can remember, I've changed some in the past already, but possibly I've missed one or more places, where it occurs.

**Comment by PeterPawn** [comment]
OK, I've missed the reason (at least a possible one) at the first glance ... the environment file uses a format, where the line starts with variable name, followed by a single TAB character (\t, 0x09) and the rest of line is variable's value. Your file uses possibly space characters (0x20), at least the copy from above.

But my other questions from above are still valid ... it's only an explanation for the error occurred.

**Comment by Tony2** [comment]
oh what a blunder I did! I didn't read the docs carefully enough and missed the proper usage.

Now I have tried `decode_export`  with a password and I could read the backup content.

Thank you for the prompt and very helpful reply.
