### ISSUE TITLE
Please rename project

### ISSUE THREAD

**Issue by Luflosi** [PeterPawn/decoder#30]
In my opinion "decoder" is too generic, see for example https://gitlab.gnome.org/World/decoder.
I propose to rename the project so that the name doesn't collide with anything else. Maybe something like fritz-decoder or fritz-config-tools?

**Comment by PeterPawn** [comment]
> Maybe something like fritz-decoder or fritz-config-tools?

There are (good) reasons, why this project does NOT carry the registered trademark "FRITZ" (or anything nearby) in its name.

Everything published under my nickname "PeterPawn" is (more or less) related to AVM's hard- and software - I can't see any needs to rename anything here.

So ... sorry, but there's no intention to follow your proposals - issue closed.

**Comment by Luflosi** [comment]
Is "FRITZ" really a  registered trademark? Fritz is a common German name, see https://en.wikipedia.org/wiki/Fritz. As such I had assumed that it was not a trademark.
You even have the project https://github.com/PeterPawn/YourFritz with Fritz in its name.
Anyways, I'm not attached to any particular name for the project, I just think it should have a different name to differentiate it from other projects with the same name.

When Linux distributions try to package two projects with the same name they will have to rename at least one of them on their own. This is bad because it makes it hard to find out how a particular project is named in the distro when one wants to install it. Different distributions may even choose different names, which makes this even more annoying.

I want to package the other decoder I linked above in NixOS but the two names would collide, so I will have to rename at least one of them on my own. It would be easier for everyone if this project had a different official name.

It would also avoid problems such as different projects incorrectly shown as multiple versions of the same projects on https://repology.org/project/decoder/versions.

I kindly ask you to reconsider changing the project name.
Thank you for your time and the quick response earlier.

**Comment by PeterPawn** [comment]
> Is "FRITZ" really a registered trademark?

https://register.dpma.de/DPMAregister/marke/registerHABM?AKZ=000916429&CURSOR=1

This registration was made for some special "nice classes" (https://en.wikipedia.org/wiki/International_(Nice)_Classification_of_Goods_and_Services) and my own use would (or at least could and I don't want to challenge anybody) collide with this registration. There are known activities by AVM to protect their trademarks, e.g. here: https://www.bawe.eu/cms/Projekte/FB-Traffic.html

And I'm trying to avoid ANY trouble with AVM regarding their trademarks.

> You even have the project https://github.com/PeterPawn/YourFritz with Fritz in its name.

That's another case ... I've started using this name at 5th of July in 2014 (at least that's the date of domain registration) and AVM was informed about this in the past, because I've used this domain to provide files and documents regarding some (security-related) findings in their firmware.

Therefore an exception in German law is important here (at least in my opinion and AVM didn't struggle with me, yet), it's paragraph 21 from the so-called "Markengesetz" (§ 21 MarkenG): https://dejure.org/gesetze/MarkenG/21.html

> I kindly ask you to reconsider changing the project name.

I've to consider even other references to the currently used name, e.g. here: 

https://www.ip-phone-forum.de/threads/wie-funktioniert-eigentlich-die-avm-verschl%C3%BCsselung-f%C3%BCr-die-einstellungen.295101/post-2226325
https://github.com/Freetz-NG/freetz-ng/blob/b5fd1e309f7631f08608a16c715dcf35b54b59bb/make/pkgs/decrypt-fritzos-cfg/decrypt-fritzos-cfg.mk#L4 (even if my project was renamed here, the source is still using my repository name)

This project does not exist in a vacuum - there are relations to others (some from MY other repositories, too) and I've to protect those at my best and not to enforce (unneeded) changes to their files.

So ... still sorry, but your arguments are not convincing here and you may - at your option - rename my project (its files will carry the original name and download source anyway) or keep its name and differentiate identical project names by their "descriptions".

**Comment by Luflosi** [comment]
Thanks for your consideration and the detailed explanation.
