### ISSUE TITLE
try to port some functionality to Windows platforms

### ISSUE THREAD

**Issue by PeterPawn** [PeterPawn/decoder#8]
- at least 'decode_export' should be runnable from any platform with ANSI C support (C99) without too much changes

**Comment by LFriede** [comment]
Hi Peter,

I compiled it on Windows yesterday and at least decode_export seems to work finde. I didn't tried the other ones. But there is a Problem with that "multi purpose" binary because it looks like it is not working that way on windows. With hardlinks you get the name of the hardlink on GetCommandLine and GetModuleFileName Winapis. With symlinks and *.lnk you get the name of the executable on both.

There are two choices now, one could hardcode the name "decoder" on Windows. But then it is not possible to rename the executable to something that not "decoder" or any of the "applets".

Second option would be to remove that feature on Windows.

What do you think about it? I think the second option will be okay because I don't think it will be used much on Windows.

**Comment by PeterPawn** [comment]
Hi,

I would think, it's not necessary in Windows to support the "applet approach", where the name of the link used to call the program is used to select a function. I'd not hesitate to replace the whole content of "decoder.c" with another version, while compiling for windows.

If I've not made any severe errors, the other files use a proper abstraction on OS-specific details. It should even be possible, to replace the "main" function in Windows with a small graphic interface for selection of functions and files - the other C sources should not need much changes therefor, as long as STDIN, STDOUT and STDERR are connected to e.g. a "memory stream" implementation.

Could you provide some more info, what you've changed? May I see the changes in any repo already? I can't find a "decoder" clone in your (GitHub) list of repos.

I'm specially interested in the questions, which compiler you've used and which crypto solution was your own choice. I did use the MS Crypto API (from PowerShell scripts) in other places, here for signing operations on firmware images: https://github.com/PeterPawn/YourFritz/blob/master/signimage/FirmwareImage.ps1 ... to keep the dependencies as small as possible. But with "libnettle" it could be possible (I didn't test it yet), to use solely "inline crypto".

Due to the support from WSL, the "pressure" to adapt the project to native Windows, was lost or at least not really heavy.

**Comment by LFriede** [comment]
I did a pull request with my changes. I agree that the "applet approach" is not necessary in Windows so I removed the hint and edited the ``decoder.c``.

Sure one could replace the whole ``decoder.c``, but I did the "lazy approach" ;)

I used msys2 (mingw compiler). I installed msys2, installed updates with ``pacman -Syuu`` and some packages with ``pacman -S make git mingw-w64-x86_64-gcc mingw-w64-x86_64-openssl``.
I built with ``make OPENSSL=y`` and didn't tried nettle yet. Maybe it's possible to use Windows crypto APIs for minimum dependecies, I've never done native crypto stuff on Windows but it'd be interesting to look at it. And since I'm ... er ... krankgeschrieben I've got some time 😄
